# Generated by Django 4.0.6 on 2022-07-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('StudentId', models.IntegerField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=50, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Email', models.CharField(max_length=50, null=True)),
                ('DateOfBirth', models.DateField()),
                ('Graduation', models.CharField(max_length=100, null=True)),
                ('YearOfPass', models.IntegerField(null=True)),
                ('BatchName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100, null=True)),
                ('Subject1', models.CharField(max_length=100, null=True)),
                ('Subject2', models.CharField(max_length=100, null=True)),
                ('Subject3', models.CharField(max_length=100, null=True)),
                ('Subject4', models.CharField(max_length=100, null=True)),
                ('Subject5', models.CharField(max_length=100, null=True)),
                ('Subject6', models.CharField(max_length=100, null=True)),
                ('Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_App.details')),
            ],
        ),
    ]
